<!doctype HTML>
<html>
	<head>
		<title>Suggestion Form</title>
	</head>
	<body>
		<form action="<?php echo $block->getBaseUrl() ?><?php echo $block->getFormAction() ?>" method= "POST">
            <h1>Have any suggestions! Please let us know .</h1>
			<label>Name</label></br>
			<input type="text" name="name" placeholder="Please enter your name" class="input-text" id="name" required/></br>
            <label>Phone Number</label></br>
			<input type="tel" name="mobile" placeholder="Please enter your mobile number" class="input-text" id="mobile" required/></br>
			<label>Email</label></br>
			<input type="email" name="email" placeholder="Please enter your email" class="input-text" id="email" required/></br>
            <label>Message</label></br>
            <textarea name="message" placeholder="Please suggest your message here" class="input-text" required></textarea></br>
    		<button type="submit" name="Submit" class="action submit primary">Submit Suggestion</button>
		</form>
		<form method="POST" action="<?php echo $block->getBaseUrl() ?>crud/index/view">
			<br>
			<button type="submit" name="Submit" class="action submit primary">View all suggestions</button>
		</form>
	</body>
</html>