<!doctype HTML>
<html>
	<head>
		<title>Registration Form</title>
	</head>
	<body>
		<form "<?php echo $block->getFormAction() ?>" method= "POST">
            <h1>Have any suggestions! Please let us know .</h1>
			<label>Name</label></br>
			<input type="text" name="name" placeholder="Please enter your name" id="name"/></br>
            <label>Phone Number</label></br>
			<input type="tel" name="mobile" placeholder="Please enter your mobile number" id="mobile"/></br>
			<label>Email</label></br>
			<input type="email" name="email" placeholder="Please enter your email" id="email"/></br>
            <label>Message</label></br>
            <textarea name="message" placeholder="Please suggest your message here"></textarea>
    		<button type="submit" name="Submit">Submit Suggestion</button>
		</form>
	</body>
</html>