<!doctype HTML>
<html>
	<head>
		<title>Registration Form</title>
	</head>
	<body>
		<form action="#" method= "POST">
            <h1>Have any suggestions! Please let us know .</h1>
			<label>Your Name</label></br>
			<input type="text" name="name" id="name"/></br>
            <label>Phone Number</label></br>
			<input type="tel" name="mobile" id="mobile"/></br>
			<label>Email</label></br>
			<input type="email" name="email" id="email"/></br>
            <label>Message</label></br>
            <textarea name="message"></textarea>
    		<input type="submit" name="Submit"></br>
		</form>
	</body>
</html>
