<?php
echo "<h2>Edit your suggestion here</h2>";
$item = $block->getDataCollection();
?>
<html>
	<head>
		<title>Suggestion Form</title>
	</head>
	<body>
		<form action="<?php echo $block->getBaseUrl() ?><?php echo $block->getFormAction() ?>" method= "POST">
			<input type="hidden" name="id" value="<?php echo $item->getId(); ?>" class="input-text" id="id" required/></br>
			<label>Name</label></br>
			<input type="text" name="name" value="<?php echo $item->getName(); ?>" class="input-text" id="name" required/></br>
            <label>Phone Number</label></br>
			<input type="tel" name="mobile" value="<?php echo $item->getMobile(); ?>" class="input-text" id="mobile" required/></br>
			<label>Email</label></br>
			<input type="email" name="email" value="<?php echo $item->getEmail(); ?>" class="input-text" id="email" required/></br>
            <label>Message</label></br>
            <textarea name="message"  class="input-text" required><?php echo $item->getMessage(); ?></textarea></br>
    		<button type="submit" name="Submit" class="action submit primary">Update</button>
		</form>
		<form method="POST" action="<?php echo $block->getBaseUrl() ?>crud/index/view">
			<br>
			<button type="submit" name="Submit" class="action submit primary">Back</button>
		</form>
	</body>
</html>