<?php
echo "<h2>All Suggestions</h2>";
$collection = $block->getDataCollection();
?>

<table>
    <center>
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Phone</th>
                <th>Email</th>
                <th>Message</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($collection as $item): ?> 
                <tr>
                    <td><?php echo $item->getId(); ?></td>
                    <td><?php echo $item->getName(); ?></td>
                    <td><?php echo $item->getMobile(); ?></td>
                    <td><?php echo $item->getEmail(); ?></td>
                    <td><?php echo $item->getMessage(); ?></td>                        
                    <td>
                    <a href="<?php echo $block->getBaseUrl() ?>crud/update/index?id=<?php echo $item->getId(); ?>" style="color:green">[Update]</a>
                    <a href="<?php echo $block->getBaseUrl() ?>crud/delete/index?id=<?php echo $item->getId(); ?>" onclick="return confirm('Are you sure want to delete?')" title="delete" style="color:red">[Delete]</a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </center>
</table>   