<!doctype HTML>
<html>
	<head>
		<title>Registration Form</title>
	</head>
	<body>
		<form action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>" method= "POST" id="form-validate">
			<label>First Name</label></br>
			<input type="text" name="firstname" id="firstname"/></br>
            <label>Last Name</label></br>
			<input type="text" name="lastname" id="lastname"/></br>
			<label>Email</label></br>
			<input type="email" name="email" id="email_address"/></br>
			<label>Password</label></br>
			<input type="password" name="password" id="password"/></br>
            <label>Confirm Password</label></br>
			<input type="password" name="password-confirmation" id="password-confirmation"/></br>
			<input type="submit" name="Submit"></br>
		</form>
	</body>
</html>
